<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eric Rue">
<meta name="author" content="Rauf">
<meta name="dcterms.date" content="2026-06-25">

<title>Corpus Characterization</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="corpus_characterization_files/libs/clipboard/clipboard.min.js"></script>
<script src="corpus_characterization_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="corpus_characterization_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="corpus_characterization_files/libs/quarto-html/popper.min.js"></script>
<script src="corpus_characterization_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="corpus_characterization_files/libs/quarto-html/anchor.min.js"></script>
<link href="corpus_characterization_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="corpus_characterization_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="corpus_characterization_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="corpus_characterization_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="corpus_characterization_files/libs/bootstrap/bootstrap-e0c3c26cf878069be9892512fea20abd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract"><span class="header-section-number">1</span> Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">2</span> Introduction</a></li>
  <li><a href="#dataset-provenance" id="toc-dataset-provenance" class="nav-link" data-scroll-target="#dataset-provenance"><span class="header-section-number">3</span> Dataset Provenance</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology"><span class="header-section-number">4</span> Methodology</a></li>
  <li><a href="#corpus-statistics" id="toc-corpus-statistics" class="nav-link" data-scroll-target="#corpus-statistics"><span class="header-section-number">5</span> Corpus Statistics</a></li>
  <li><a href="#quality-taxonomy" id="toc-quality-taxonomy" class="nav-link" data-scroll-target="#quality-taxonomy"><span class="header-section-number">6</span> Quality Taxonomy</a>
  <ul class="collapse">
  <li><a href="#clean" id="toc-clean" class="nav-link" data-scroll-target="#clean"><span class="header-section-number">6.1</span> Clean</a></li>
  <li><a href="#skewed" id="toc-skewed" class="nav-link" data-scroll-target="#skewed"><span class="header-section-number">6.2</span> Skewed</a></li>
  <li><a href="#complex-layout" id="toc-complex-layout" class="nav-link" data-scroll-target="#complex-layout"><span class="header-section-number">6.3</span> Complex Layout</a></li>
  <li><a href="#faded" id="toc-faded" class="nav-link" data-scroll-target="#faded"><span class="header-section-number">6.4</span> Faded</a></li>
  <li><a href="#damaged-content-loss" id="toc-damaged-content-loss" class="nav-link" data-scroll-target="#damaged-content-loss"><span class="header-section-number">6.5</span> Damaged / Content Loss</a></li>
  <li><a href="#secondary-tag-has_latin_chars" id="toc-secondary-tag-has_latin_chars" class="nav-link" data-scroll-target="#secondary-tag-has_latin_chars"><span class="header-section-number">6.6</span> Secondary Tag: has_latin_chars</a></li>
  </ul></li>
  <li><a href="#evaluation-subset" id="toc-evaluation-subset" class="nav-link" data-scroll-target="#evaluation-subset"><span class="header-section-number">7</span> Evaluation Subset</a></li>
  <li><a href="#challenges-and-implications-for-preprocessing" id="toc-challenges-and-implications-for-preprocessing" class="nav-link" data-scroll-target="#challenges-and-implications-for-preprocessing"><span class="header-section-number">8</span> Challenges and Implications for Preprocessing</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">9</span> Limitations</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">10</span> References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="corpus_characterization.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Corpus Characterization</h1>
<p class="subtitle lead">AlbertoChestnut/telugu-ocr — Phase 1 Deliverable</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Eric Rue </p>
             <p>Rauf </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 25, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="abstract" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Abstract</h1>
<p>This document characterizes the corpus used for a Telugu OCR pipeline built as a class deliverable for CSCI/DASC 6020 (Summer 2026). Working from the publicly available <code>AlbertoChestnut/telugu-ocr</code> HuggingFace dataset, we developed against a five-book subset comprising 415 paired page images and ground-truth Unicode text files. We built an inventory script that records per-page metadata (image dimensions, file sizes, pairing integrity), computed corpus statistics, defined a five-bucket quality taxonomy by structured visual inspection of a stratified 97-page sample, and froze a stratified 30-page evaluation subset (six pages per bucket) that all downstream phases score against. The corpus is dominated by visually clean pages (approximately two-thirds of the sample) with a long tail of skewed scans, complex layouts, faded ink, and damaged pages that include scanning artifacts and physical damage. These quality conditions directly determine the preprocessing pipeline scope in Phase 2 and provide the per-bucket axis along which model performance is reported in Phase 5.</p>
</section>
<section id="introduction" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introduction</h1>
<p>The CSCI/DASC 6020 Summer 2026 class project asks teams to build an end-to-end Telugu OCR pipeline using vision-capable large language models, plus a validation framework that scores OCR quality without depending on human ground truth. The project rubric is structured around seven dimensions; this document addresses Dimension 1 (Corpus Characterization and Problem Scoping). Subsequent documents and deliverables address the remaining dimensions: preprocessing (Dimension 2), OCR pipeline and model comparison (Dimension 3), LLM-assisted validation (Dimension 4), analysis (Dimension 5), code quality (Dimension 6), and the final written report (Dimension 7).</p>
<p>Corpus characterization comes first in our sequence because every downstream decision depends on understanding what kinds of pages the OCR system has to handle. Preprocessing stage selection (deskew, binarization, denoise, contrast enhancement) is justified by the visual conditions actually present in the corpus. Model selection between vision-capable LLMs and classical OCR is justified by per-bucket performance expectations — vision LLMs are expected to outperform classical OCR specifically on the harder buckets (complex layout, damaged pages). Sample size choices for evaluation are justified by the corpus distribution. Without an explicit characterization phase, downstream design decisions would rest on assumption rather than evidence.</p>
<p>The document is structured as follows. We first describe the dataset’s provenance and our reasons for choosing it. We then describe the methodology used to characterize the corpus — inventory, statistics, taxonomy, and stratified subset selection. Section “Corpus Statistics” presents the headline numerical findings. Section “Quality Taxonomy” defines five quality buckets and their inclusion criteria. Section “Evaluation Subset” describes the 30-page frozen evaluation set and its rationale. Section “Challenges and Implications for Preprocessing” links each quality bucket to the preprocessing stage that targets it, establishing the per-bucket hypotheses that Phase 5 tests. We close with limitations and references.</p>
</section>
<section id="dataset-provenance" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Dataset Provenance</h1>
<p>We use the publicly available <code>AlbertoChestnut/telugu-ocr</code> dataset hosted on HuggingFace Hub. The dataset consists of paired image and text files: for every <code>.jpg</code> page scan there is a corresponding <code>.txt</code> file containing Unicode-encoded Telugu text. The dataset author collected approximately 221 books totalling roughly 13 GB of paired files; multiple other student teams in CSCI/DASC 6020 also converged on this dataset for their Phase 1 corpus, which we mention here for transparency.</p>
<p>The instructor announced on 27 May 2026 that a course-provided corpus would be delivered “next week,” but as of project start that corpus had not been distributed and multiple teams’ follow-up requests went unanswered. We treated the schedule risk as binding and adopted <code>AlbertoChestnut/telugu-ocr</code> rather than wait. Our final report’s methodology section discloses this choice and the alternative we did not pursue.</p>
<p>The paired-file structure of <code>AlbertoChestnut/telugu-ocr</code> is essential to our approach. The project specification asks teams to “sample 30-50 pages across the quality spectrum and annotate them manually” to produce ground-truth text for evaluation. Because the upstream dataset already ships paired images and ground-truth text, we skip manual annotation entirely. Our work is to characterize and stratify what we have, not to create new ground-truth.</p>
<p>For reproducibility, our download script pins the exact dataset revision (commit <code>f2bd895b4932b648174a8f47066f4166469933a0</code>) so that both team members and future readers can re-download the identical files. The pinned revision is documented in <code>scripts/download_dataset.py</code>.</p>
</section>
<section id="methodology" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Methodology</h1>
<p>Our corpus characterization proceeded in four sequential steps. Each step produced an artifact consumed by the next.</p>
<p><strong>Step 1 — Inventory.</strong> A Python script walks the local dataset directory, pairs each <code>.jpg</code> with its matching <code>.txt</code> file by filename stem, extracts per-page metadata (image dimensions via Pillow, file sizes from <code>stat</code>), and writes the result to <code>data/external/corpus_inventory.csv</code>. The script also verifies the paired-file invariant (every <code>.jpg</code> has a matching <code>.txt</code>) and runs an encoding spot-check on a small random sample of text files to confirm UTF-8 NFC encoding. The inventory CSV becomes the canonical “table of contents” for every downstream phase.</p>
<p><strong>Step 2 — Statistics.</strong> A Jupyter notebook loads the inventory CSV and produces four distribution plots: image dimension scatter, estimated DPI distribution, ground-truth text length distribution, and image file-size distribution. The notebook also writes a small JSON file (<code>data/external/corpus_stats.json</code>) with headline numerical findings used by the report and by downstream design decisions.</p>
<p><strong>Step 3 — Quality taxonomy.</strong> We define five quality buckets by structured visual inspection. A stratified sample of 97 pages was browsed page-by-page, observations were collected, and the observations were clustered into five buckets with concrete, OCR-relevant inclusion criteria. The buckets are documented in detail in the Quality Taxonomy section below.</p>
<p><strong>Step 4 — Stratified evaluation subset.</strong> From the 97 hand-tagged pages we draw six pages per bucket (30 pages total) with a fixed random seed, write the selection to <code>data/external/eval_subset.csv</code>, and copy the 30 image+text pairs to <code>data/external/eval_subset/</code>. This frozen subset is the evaluation target for every Phase 3 OCR run, every Phase 4 CER/WER computation, and every Phase 5 per-bucket analysis.</p>
<p><strong>Subset rather than full corpus.</strong> We work with a five-book subset (415 paired pages, approximately 190 MB) rather than the full 13 GB corpus. The motivation is iteration speed: with 415 pages we can re-run the inventory, the preprocessing pipeline, and the OCR adapters across the full local set in minutes rather than hours, which matters in a four-day delivery schedule. The five-book subset covers the file-size and book-format variation observed in the full upstream listing, so we expect it to be representative for the kinds of statistical and quality claims this project makes. We disclose the subset choice in the Limitations section.</p>
<p><strong>No manual annotation.</strong> As stated in the previous section, we do not annotate ground-truth text. The dataset’s paired-file structure provides it. Time we would otherwise spend on annotation goes to building a stronger pipeline.</p>
</section>
<section id="corpus-statistics" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Corpus Statistics</h1>
<p>The 5-book subset comprises <strong>415 paired pages</strong> across <strong>5 books</strong>, drawn from the upstream <code>AlbertoChestnut/telugu-ocr</code> HuggingFace dataset at the pinned commit. Per-book page counts:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Book ID</th>
<th style="text-align: right;">Pages</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Kalidasa-Charitra_by_chilakamarthi_lakshminarasimham</td>
<td style="text-align: right;">133</td>
</tr>
<tr class="even">
<td>2015.385293.Paarijaata-Paharanamu</td>
<td style="text-align: right;">110</td>
</tr>
<tr class="odd">
<td>2015.389095.Shabhuka-Vadha</td>
<td style="text-align: right;">75</td>
</tr>
<tr class="even">
<td>2015.328360.Andhra-Mahaniyulu</td>
<td style="text-align: right;">60</td>
</tr>
<tr class="odd">
<td>2030020025431_-_chitra_leikhanamu</td>
<td style="text-align: right;">37</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>415</strong></td>
</tr>
</tbody>
</table>
<p>Aggregate page-level statistics (from <code>data/external/corpus_stats.json</code>):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total books</td>
<td>5</td>
</tr>
<tr class="even">
<td>Total pages</td>
<td>415</td>
</tr>
<tr class="odd">
<td>Median image width</td>
<td>1500 pixels (uniform)</td>
</tr>
<tr class="even">
<td>Median image height</td>
<td>2261 pixels</td>
</tr>
<tr class="odd">
<td>Mean ground-truth text length</td>
<td>3,145 chars</td>
</tr>
<tr class="even">
<td>Median ground-truth text length</td>
<td>2,882 chars</td>
</tr>
<tr class="odd">
<td>Median file size</td>
<td>478 KB</td>
</tr>
<tr class="even">
<td>DPI estimate (from typical 6-inch book width)</td>
<td>~250 DPI</td>
</tr>
<tr class="odd">
<td><code>image_width_uniform</code></td>
<td><code>true</code></td>
</tr>
</tbody>
</table>
<p><strong>The image-width distribution is degenerate</strong>: every image in the subset is exactly 1500 pixels wide. We had originally planned to plot a DPI histogram; with a single observed width, that collapses to a single value (~250 DPI inferred from typical Telugu book physical width). Rather than fake a histogram with a single bar, we report the uniformity finding directly and set <code>image_width_uniform: true</code> in the corpus stats JSON. The Phase 2-5 pipeline does not depend on per-image DPI variation; this finding is informational.</p>
<p>Headline distribution plots from <code>notebooks/01_corpus_characterization.ipynb</code>:</p>
<div class="quarto-layout-panel" data-layout-ncol="1">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/corpus/file_size_distribution.png" class="img-fluid figure-img" style="width:85.0%"></p>
<figcaption>File-size distribution across the 5-book subset</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/corpus/image_dimensions_scatter.png" class="img-fluid figure-img" style="width:85.0%"></p>
<figcaption>Image-dimension scatter showing the uniform 1500-pixel width</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/corpus/text_length_distribution.png" class="img-fluid figure-img" style="width:85.0%"></p>
<figcaption>Per-page ground-truth text-length distribution</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="quality-taxonomy" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Quality Taxonomy</h1>
<p>To make per-condition claims later in the project — for example, “our OCR pipeline performs differently on pages with scanning artifacts versus clean pages” — we partition the corpus into five quality buckets. The buckets are defined by visual features observable directly from the page image, without reading the Telugu text.</p>
<p>We arrived at these five buckets by a structured browsing pass. A stratified sample of 47 pages (5 books × 5 image-file-size quintiles, drawn with a fixed random seed for reproducibility) was reviewed page by page and observations were collected. The observations were then clustered into the five buckets below. Bucket definitions are intentionally concrete — they describe specific visual features rather than impressionistic good-versus-bad judgments — so a second annotator should be able to apply them to a new page and reach the same bucket approximately 80% of the time.</p>
<p>When multiple features are present on a single page, the buckets are applied with the following priority order (most severe first):</p>
<ol type="1">
<li><strong>Damaged / Content Loss</strong></li>
<li><strong>Complex Layout</strong></li>
<li><strong>Faded</strong></li>
<li><strong>Skewed</strong></li>
<li><strong>Clean</strong> (default)</li>
</ol>
<p>A page that is both skewed and damaged is assigned to Damaged. A page that is both faded and has complex layout is assigned to Complex Layout. The order reflects how strongly each feature dominates OCR difficulty.</p>
<section id="clean" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="clean"><span class="header-section-number">6.1</span> Clean</h2>
<p><strong>Definition.</strong> Pages with crisp printed Telugu body text, the page sitting square in the scan frame (no visible tilt), single-column layout with no embedded illustrations or text-in-boxes, and no significant scanning artifacts or fading. This is the default category — pages go here unless one of the other four buckets clearly applies.</p>
<p><strong>Inclusion criteria</strong> (all must hold):</p>
<ul>
<li>Body-text characters are uniformly legible</li>
<li>Page tilt is visually undetectable (less than approximately 1 degree)</li>
<li>Layout is single-column flowing text</li>
<li>No drawings, illustrations, or text bounded in boxes or frames</li>
<li>No visible scanning artifacts (no white bands, no severe edge fading, no severe smudging)</li>
<li>No visible physical damage to the source page</li>
</ul>
<p><strong>OCR relevance.</strong> Baseline. The expected lower bound on CER (best case) across the corpus comes from this bucket. Phase 5 reports per-bucket CER so the Clean baseline is visible separately from harder cases.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/corpus/quality_examples/clean.jpg" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Example: clean page.</figcaption>
</figure>
</div>
</section>
<section id="skewed" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="skewed"><span class="header-section-number">6.2</span> Skewed</h2>
<p><strong>Definition.</strong> Pages where the printed content is visibly tilted relative to the image frame, indicating the physical page was not aligned square to the scanner glass when captured.</p>
<p><strong>Inclusion criteria</strong> (all must hold):</p>
<ul>
<li>Body-text lines are clearly not horizontal — a visible tilt is present</li>
<li>Tilt is at least approximately 2 degrees (visually unambiguous)</li>
<li>Text is otherwise legible — not also faded, damaged, or in complex layout</li>
</ul>
<p><strong>OCR relevance.</strong> This is the bucket directly addressed by the deskew preprocessing stage in Phase 2. We expect to observe a measurable CER improvement on this bucket between the raw-OCR and preprocessed-OCR runs in Phase 5.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/corpus/quality_examples/skewed.jpg" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Example: skewed page.</figcaption>
</figure>
</div>
</section>
<section id="complex-layout" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="complex-layout"><span class="header-section-number">6.3</span> Complex Layout</h2>
<p><strong>Definition.</strong> Pages where the structure deviates from single-column flowing text. Includes pages with embedded illustrations, text inside boxes or frames, multi-column layouts, tables, or pages dominated by ornamental content rather than body text.</p>
<p><strong>Inclusion criteria</strong> (any one is sufficient):</p>
<ul>
<li>Page contains at least one drawing or illustration covering approximately 10% or more of the page area</li>
<li>Page contains text bounded in boxes, frames, or borders (not merely decorative dividers between paragraphs)</li>
<li>Page uses a multi-column body-text layout</li>
<li>Page contains tabular data</li>
<li>Page is dominated by visual or ornamental content rather than body text (for example, a title page)</li>
</ul>
<p><strong>Disambiguation.</strong> Normal Telugu typographic features such as decorative section dividers (rows of stars or dots between paragraphs), ornamental borders along the page edge, or numbered verses are NOT sufficient on their own to place a page in Complex Layout. These are standard features of Telugu publishing and appear throughout otherwise-Clean pages.</p>
<p><strong>OCR relevance.</strong> Vision-LLM OCR (Gemini) is expected to handle complex layouts gracefully, whereas classical OCR (Tesseract) may produce reading-order errors or skip non-text regions inconsistently. This bucket is a key axis for the model-comparison story in Phase 5.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/corpus/quality_examples/complex_layout.jpg" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Example: complex-layout page.</figcaption>
</figure>
</div>
</section>
<section id="faded" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="faded"><span class="header-section-number">6.4</span> Faded</h2>
<p><strong>Definition.</strong> Pages where the text is fully present but appears low-contrast (light ink, possibly small type) such that individual characters are harder to read than on a Clean page. The fading is approximately uniform across the page, not localized to one band or edge.</p>
<p><strong>Inclusion criteria</strong> (all must hold):</p>
<ul>
<li>Text is visibly lighter than a Clean page drawn from the same book</li>
<li>The low-contrast affects a substantial portion of the page (more than a small area)</li>
<li>No content is physically missing — every character is still drawable if traced carefully</li>
</ul>
<p><strong>Disambiguation.</strong></p>
<ul>
<li>If only the edges of the page are faded but the center is sharp, the page is assigned to Damaged (the loss is localized).</li>
<li>If only one horizontal band is affected, the page is Damaged.</li>
<li>If the page is uniformly low-contrast partly because of ink bleed-through from the reverse page, it remains Faded as long as the bleed-through does not itself obscure characters.</li>
</ul>
<p><strong>OCR relevance.</strong> This is the bucket directly addressed by the binarization stage in Phase 2. We expect to observe a measurable CER improvement on this bucket between the raw-OCR and preprocessed-OCR runs in Phase 5.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/corpus/quality_examples/faded.jpg" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Example: faded page.</figcaption>
</figure>
</div>
</section>
<section id="damaged-content-loss" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="damaged-content-loss"><span class="header-section-number">6.5</span> Damaged / Content Loss</h2>
<p><strong>Definition.</strong> Pages where content is physically lost or unrecoverable due to scanning artifacts, physical damage to the source page, or severe localized degradation. Distinguished from Faded by the localized or discrete nature of the loss — a Damaged page has specific regions where information has been destroyed, not merely a uniform reduction in contrast.</p>
<p><strong>Inclusion criteria</strong> (any one is sufficient):</p>
<ul>
<li>White-band horizontal artifact across one or more text lines (scanning or photocopier artifact)</li>
<li>Page is visibly torn and reassembled with a discernible alignment offset</li>
<li>Significant ink smudging that obliterates words or letters</li>
<li>Severe edge fading where edge words are lost entirely (not merely lighter than the page interior)</li>
<li>Severe ink bleed-through where text from the reverse page is illegibly mixed with the front-page text such that characters cannot be reliably read</li>
<li>Any other visible damage that has removed or obscured printed content</li>
</ul>
<p><strong>OCR relevance.</strong> This bucket sets the noise floor on OCR quality. Preprocessing cannot recover lost content. The corpus-wide CER reported in Phase 5 is partially bounded by the fraction of pages in this bucket, which is important context for interpreting the headline results: a 10% mean CER on a corpus with 15% Damaged pages is a very different story than a 10% mean CER on a corpus that is entirely Clean.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/corpus/quality_examples/damaged.jpg" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Example: damaged page.</figcaption>
</figure>
</div>
</section>
<section id="secondary-tag-has_latin_chars" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="secondary-tag-has_latin_chars"><span class="header-section-number">6.6</span> Secondary Tag: has_latin_chars</h2>
<p>Distinct from the five primary buckets, we tag each page in the inventory CSV with a boolean <code>has_latin_chars</code> indicating whether the page contains any English, Roman, or Arabic numerals or Latin-script characters. Common cases include page numbers, numbered verse markers (a Telugu publishing convention where individual shlokas or verses are numbered with English digits), and citations.</p>
<p>This is captured as a column on the inventory CSV rather than as a primary bucket because the feature is independent of the five quality dimensions — a page with English page numbers can simultaneously be Clean, Faded, or Damaged. In Phase 5 we use this tag for an additional analysis cut: comparing Gemini and Tesseract performance specifically on multi-script pages, where Tesseract’s <code>--lang=tel</code> configuration is expected to mishandle the Latin characters while Gemini’s vision model is expected to handle them natively.</p>
</section>
</section>
<section id="evaluation-subset" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Evaluation Subset</h1>
<p>The evaluation subset is a frozen set of 30 pages drawn stratified across the five quality buckets — six pages per bucket. It lives at <code>data/external/eval_subset.csv</code> (the page identifiers and bucket tags) and <code>data/external/eval_subset/</code> (the copied image and text files). The selection script and a random seed of 42 make the draw fully reproducible: re-running <code>scripts/select_eval_subset.py --seed 42</code> against the same tagged source pool produces the identical 30-page set.</p>
<p><strong>Why stratified rather than random.</strong> A random sample drawn from the inventory would mirror the corpus distribution, which is heavily Clean-dominated (approximately two-thirds of our 97-page tagged pool was tagged Clean). On such a sample, a model that performs well on Clean pages and poorly on Damaged pages would produce a high overall average even if it failed on every Damaged page in the corpus. Stratified sampling — drawing equal numbers from each bucket — gives us enough statistical power per bucket to make conditional claims like “this preprocessing stage improves CER on Skewed pages by X% but has no effect on Damaged pages.” Those conditional claims are what the project’s analysis dimension actually asks for, and a random sample would not support them.</p>
<p>We deliberately accept the artificial balance as a methodological choice. Phase 5 will report both the per-bucket CERs (computed on the balanced eval subset) and a corpus-weighted summary CER (computed by reweighting the per-bucket results by their estimated corpus prevalence), so the reader sees both views.</p>
<p><strong>Why the eval subset is frozen rather than resampled per run.</strong> If we re-drew the evaluation pages between Phase 3 and Phase 4 — or even between two different OCR runs in Phase 3 — the resulting CERs would be incomparable, and apparent improvements between configurations would be confounded with the random variation in page selection. Freezing the set at the start of Phase 3, committing it to git, and using <code>git diff</code> to verify it has not changed makes all per-bucket comparisons throughout the project genuinely fair.</p>
<p><strong>Tagged source pool.</strong> The 30-page evaluation subset is drawn from a tagged pool of 97 pages built across two browsing batches. The first batch (47 pages) was stratified across image-file-size quintiles and books to spread coverage broadly. After tagging the first batch, the Skewed bucket only contained two pages, which is too few for any per-bucket statistical claim. A second batch (50 pages) drew randomly from each book to top up the rare buckets; after tagging, Skewed reached six pages and the threshold for inclusion in the stratified draw. The full 97-page tagged pool is committed at <code>data/external/quality_tags.csv</code> for traceability.</p>
</section>
<section id="challenges-and-implications-for-preprocessing" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Challenges and Implications for Preprocessing</h1>
<p>The five quality buckets are not just a corpus description; they directly determine the preprocessing pipeline scope. Each bucket establishes a hypothesis about which preprocessing stage is expected to help most. Phase 5 tests those hypotheses against per-bucket CER measurements; this section names the hypotheses explicitly.</p>
<p><strong>Skewed pages and deskew preprocessing.</strong> Pages where the printed content is visibly tilted in the scan frame interact badly with classical OCR because line-segmentation algorithms typically expect horizontal text rows. We expect the Skewed bucket to show the strongest before-and-after CER improvement when a deskew stage is added to the preprocessing pipeline. Deskew is therefore Stage 1 of our Phase 2 pipeline.</p>
<p><strong>Faded pages and binarization preprocessing.</strong> Pages where the text is uniformly low-contrast — light ink against an off-white background — are harder for both classical OCR and vision LLMs because individual characters are less visually distinct. Adaptive binarization converts the page to a clean black-on-white representation in which character strokes are sharper. We expect the Faded bucket to show a strong before-and-after CER improvement when a binarization stage is added. Binarization is therefore Stage 2 of our Phase 2 pipeline.</p>
<p><strong>Damaged pages and the noise floor.</strong> Pages where content is physically lost — scanning artifacts, torn-and-reassembled pages, severe smudging — cannot be recovered by preprocessing because the information is genuinely missing. We do not hypothesize any CER improvement on Damaged pages from any preprocessing stage. Instead, we use the Damaged bucket to characterize the noise floor on the corpus: the lower bound on achievable CER given the dataset as shipped. A 5% mean CER on a corpus with 7% Damaged pages is a very different story than a 5% mean CER on a fully clean corpus, and we report this context in Phase 5.</p>
<p><strong>Complex Layout pages and the model-comparison story.</strong> Pages containing illustrations, multi-column text, text in frames or boxes, or other non-uniform structure are where vision-capable LLMs are expected to most clearly outperform classical OCR. Tesseract with <code>--lang=tel</code> and <code>--psm 6</code> assumes a single uniform block of text, which complex pages violate. Vision LLMs handle layout natively and are not expected to fail on the same modes. The Complex Layout bucket therefore provides the strongest evidence for the Phase 5 model-comparison narrative.</p>
<p><strong>Clean pages and the baseline.</strong> Clean pages are the corpus majority and the lower-bound case for OCR quality. The Clean bucket establishes our best-achievable CER on the corpus given a particular model. Strong performance on Clean is necessary but not sufficient — a model can score zero CER on Clean pages and still fail spectacularly on the other four buckets, which is the entire reason for stratified evaluation.</p>
</section>
<section id="limitations" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Limitations</h1>
<p>This characterization has explicit limitations that the reader should keep in mind when interpreting the results in subsequent phases.</p>
<p><strong>Subset rather than full corpus.</strong> We work with a five-book subset (415 pages) rather than the full 13 GB upstream corpus (approximately 221 books). The subset was chosen to fit a four-day delivery schedule; if a particular book in the full corpus contains visual conditions absent from our five books, our taxonomy will not cover them and our eval subset will not represent them. We mitigated this risk by drawing the subset across file-size quintiles, which exposes the most variation per dollar of disk space, but the risk is real and material to any claim about “the AlbertoChestnut corpus” as a whole.</p>
<p><strong>JPEG compression as an unaddressed noise floor.</strong> Every page in the corpus is stored as a compressed JPEG. This is a publication choice by the dataset author (likely to keep the full 13 GB tractable to host) but it imposes a compression-artifact noise floor on the source material that no preprocessing or OCR model in our pipeline can overcome. The granularity that human observers notice on inspection is partly real ink texture and partly JPEG artifact; we cannot disentangle them.</p>
<p><strong>Visual-only taxonomy by non-Telugu-reading annotators.</strong> Neither team member reads Telugu. Our quality taxonomy is therefore purely visual — we bucket pages by features observable without reading the text. A Telugu-reading annotator might define different or additional buckets (for example, separating “well-typeset modern reprints” from “first-edition typesetting”). The buckets we use are sufficient for OCR-relevant evaluation, but they are not the taxonomy a literary scholar of Telugu publishing would draw.</p>
<p><strong>Ground-truth quality.</strong> The dataset’s ground-truth <code>.txt</code> files are community-contributed and we have not independently verified them. If the upstream ground truth has systematic errors, those errors will appear in our reported CERs in ways we cannot easily distinguish from OCR errors. Phase 4’s LLM validation framework partially stress-tests this concern by independently scoring OCR output for plausibility, but the reader should not interpret reported CER values as character-perfect ground truth.</p>
<p><strong>Per-bucket sample size of six.</strong> Six pages per bucket gives just enough statistical power to identify large effects between configurations (for example, “deskew preprocessing roughly halves CER on Skewed pages”). It is not enough to identify subtle differences. Phase 5 reports per-bucket effect sizes and discusses statistical significance honestly.</p>
</section>
<section id="references" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> References</h1>
<ul>
<li>AlbertoChestnut. <em>Telugu OCR Dataset.</em> HuggingFace Hub, 2026. <a href="https://huggingface.co/datasets/AlbertoChestnut/telugu-ocr" class="uri">https://huggingface.co/datasets/AlbertoChestnut/telugu-ocr</a>. Pinned revision: <code>f2bd895b4932b648174a8f47066f4166469933a0</code>. Accessed June 2026.</li>
<li>Morris, A. C., Maier, V., and Green, P. <em>From WER and RIL to MER and WIL: improved evaluation measures for connected speech recognition.</em> INTERSPEECH 2004. (Background on word- and character-error-rate metrics used in Phase 4.)</li>
<li>Allaire, J. J., et al.&nbsp;<em>Quarto.</em> <a href="https://quarto.org/" class="uri">https://quarto.org/</a>. Documentation accessed June 2026.</li>
<li>Smith, R. <em>An Overview of the Tesseract OCR Engine.</em> In Proceedings of the Ninth International Conference on Document Analysis and Recognition, 2007.</li>
<li>Google. <em>Gemini API documentation.</em> <a href="https://ai.google.dev/gemini-api/docs" class="uri">https://ai.google.dev/gemini-api/docs</a>. Accessed June 2026.</li>
</ul>
<div class="callout callout-style-simple callout-note callout-empty-content">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">

</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>